name: 'outdated-parrot'
description:
  'Action to parrot "outdated" pull request comments back onto the files changed
  view as annotations'
author: 'IRHayfield'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'feather'
  color: 'green'

# Define your inputs here.
inputs:
  add-hash:
    description:
      'Add the hash of the git commit which the comment was made against to the
      comment annotation'
    required: false
    default: false
  add-diff:
    description: 'Add diff link to the comment annotation'
    required: false
    default: true
  add-discussion:
    description: 'Add discussion link to the comment annotation'
    required: false
    default: true
  add-regenerate:
    description: 'Add regenerate link to the comment annotation'
    required: false
    default: false
  add-standalone-regenerate:
    description:
      'Add stand-alone regenerate link annotation that can be used to regenerate
      all annotations'
    required: false
    default: true
  get-latest-line:
    description: 'Find current line location using git blame'
    required: false
    default: true

runs:
  using: node20
  main: dist/index.js
