name: Outdated Parrot

on:
  pull_request:
    types:
      - synchronize

permissions:
  contents: read
  issues: write

jobs:
  parrot:
    name: Parrot outdated comments
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code for git blame
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run parrot action
        uses: irhayfield/outdated-parrot@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
